global:
  name: Continuous Delivery Landscape
  short_name: CDF
  repo: cdfoundation/landscape
  website: 'https://landscape.cd.foundation'
  short_domain: l.cd.foundation
  company_url: 'https://cd.foundation'
  email: info@cd.foundation
  meta:
    title: Continuous Delivery Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@CDeliveryFdn'
    google_site_verification: x3QPMhFwxg1ZMS9tlhhgwIJKokbEkt1zByMLMXiqnds
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  membership: CNCF Members  
  flags:
    cncf_sandbox: false
    companies: CDF Members
twitter:
  search: landscape.cd.foundation
  url: 'https://landscape.cd.foundation'
  text: CDF Landscape from @CDeliveryFdn
relation:
  label: CDF Relation
  url: cd.foundation
  values:
    - id: hosted
      label: CDF Projects
      children:
        - id: graduated
          label: Graduated CDF Projects
          prefix: CDF
          tag: Graduated
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: CDF Graduated
          big_picture_color: 'rgb(24,54,114)'
        - id: incubating
          label: Incubating CDF Projects
          prefix: CDF
          tag: Incubating
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: CDF Incubating
          big_picture_color: 'rgb(83, 113, 189)'
    - id: company
      label: CDF Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: CDF Member Products/Projects
      tag: CDF Member
    - id: false
      label: Non-CDF Member Products/Projects
      url: 'no'
membership:
  Platinum:
    name: CNCF
    label: Platinum Member
    end_user_label: Platinum End User Member
    funding: Platinum
    is_large: true
  General:
    name: CNCF
    label: General Member
    end_user_label: General End User Member
    funding: General
    is_large: true
  Silver:
    name: CNCF
    label: Silver Member
    end_user_label: Silver End User Member
    funding: Silver
  Academic:
    name: CNCF
    label: Academic Member
    end_user_label: Academic End User Member
    funding: Academic
  Nonprofit:
    name: CNCF
    label: Nonprofit Member
    end_user_label: Nonprofit End User Member
    funding: Nonprofit
  End User Supporter:
    name: CNCF
    label: End User Supporter
    funding: End User Supporter
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: 'https://www.crunchbase.com/organization/linux-foundation'
  cncf:
    name: CNCF
    label: Project
    funding: CNCF
  'false':
    funding: 'No'
home:
  header: >
    <h1>Continuous Delivery Landscape</h1> The Continuous Delivery Foundation landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: 'https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/?utm_source=cdf_landscape&utm_medium=web&utm_campaign=kccncna19'
    image: /images/info1.jpg
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Linux Foundation CI/CD Landscape
    fullscreen_header: See the interactive landscape at l.cd.foundation
    method: getGroupedItemsForCncfBigPicture
    size:
      width: 1115
      height: 770
    fullscreen_size:
      width: 1155
      height: 840
    elements:
      - type: HorizontalCategory
        category: Continuous Delivery Pipeline Orchestration
        rows: 3
        width: 280
        height: 160
        top: 0
        left: 0
        color: 'rgb(78,171,207)'
        fit_width: true
      - type: HorizontalCategory
        category: Continuous Delivery Automation
        rows: 3
        width: 460
        height: 160
        top: 0
        left: 300
        color: 'rgb(104, 145, 145)'
        fit_width: true
      - type: HorizontalCategory
        category: Component Sharing and Library Management
        rows: 3
        width: 260
        height: 160
        top: 0
        left: 780
        color: 'rgb(43, 142, 136)'
        fit_width: true
      - type: HorizontalCategory
        category: Infrastructure Deployments, Container Registry, Application Definition and Image Build
        rows: 3
        width: 400
        height: 160
        top: 190
        left: 0
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: HorizontalCategory
        category: DevSecOps, Analytics and Monitoring
        rows: 3
        width: 280
        height: 160
        top: 190
        left: 420
        color: 'rgb(64, 89, 163)'
        fit_width: true
      - type: HorizontalCategory
        category: CDF Members
        rows: 8
        width: 1200
        height: 320
        top: 380
        left: 0
        color: 'rgb(74, 131, 104)'
        fit_width: true
test:
  header: Continuous Delivery Landscape
  section: CDF Members
  logo: tekton-pipelines.svg
update_server:
  ip: 147.75.106.211
  update_hour: 0
  update_minute: 0
