global:
  name: Continuous Delivery Landscape
  short_name: CDF
  repo: cdfoundation/landscape
  website: https://landscape.cd.foundation
  short_domain: l.cd.foundation
  company_url: https://cd.foundation
  email: info@cd.foundation
  self: https://www.crunchbase.com/organization/continuous-delivery-foundation-cdf
  slack_channel: T08PSQ7BQ/BNL6EUY3X/Y1e4mHQl77qnLRi8eQCwtKT0
  meta:
    title: Continuous Delivery Landscape
    fb_admin: alex.contini.94
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    twitter: '@CDeliveryFdn'
    google_site_verification: apI3BLUsW1CCRZpZ6XDsuvJyJSRVc4UZ-yRwbzP3ytk
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  membership: CDF Members
  flags:
    companies: CDF Members
twitter:
  search: landscape.cd.foundation
  url: https://landscape.cd.foundation
  text: CDF Landscape from @CDeliveryFdn
relation:
  label: CDF Relation
  url: cd.foundation
  values:
    - id: hosted
      label: CDF Projects
      children:
        - id: graduated
          label: Graduated CDF Projects
          prefix: CDF
          tag: Graduated
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: CDF Graduated
          big_picture_color: rgb(24,54,114)
        - id: incubating
          label: Incubating CDF Projects
          prefix: CDF
          tag: Incubating
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: CDF Incubating
          big_picture_color: rgb(83, 113, 189)
    - id: company
      label: CDF Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: CDF Member Products/Projects
      tag: CDF Member
    - id: false
      label: Non-CDF Member Products/Projects
      url: 'no'
membership:
  Premier:
    name: CDF
    label: Premier Member
    end_user_label: Premier End User Member
    funding: Premier
    is_large: true
  General:
    name: CDF
    label: General Member
    end_user_label: General End User Member
    funding: General
  End User:
    name: CDF
    label: End User
    funding: End User
    enduser: true
  Associate:
    name: CDF
    label: Associate
    funding: Associate
    enduser: true
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  cdf:
    name: CDF
    label: Project
    funding: CDF
  'false':
    funding: 'No'
home:
  header: >
    <h1>Continuous Delivery Landscape</h1> The Continuous Delivery Foundation landscape (<a target="_blank" href="images/landscape.png">png</a>, <a
    target="_blank" href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF
    landscape</a> and based on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/?utm_source=cdf_landscape&utm_medium=web&utm_campaign=kccncna21
    image: /images/kubecon_na_21.jpg
    title: KubeCon + CloudNativeCon NA 2021 Virtual
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Linux Foundation CI/CD Landscape
    fullscreen_header: See the interactive landscape at l.cd.foundation
    elements:
      - type: HorizontalCategory
        category: CI & Pipeline Orchestration
        rows: 3
        width: 870
        height: 160
        top: 0
        left: 0
        color: rgb(29,119,164)
        fit_width: true
      - type: HorizontalCategory
        category: Continuous Automation
        rows: 3
        width: 310
        height: 160
        top: 0
        left: 890
        color: rgb(19,105,73)
        fit_width: true
      - type: HorizontalCategory
        category: Config & Library Management
        rows: 3
        width: 460
        height: 120
        top: 170
        left: 0
        color: rgb(79,121,13)
        fit_width: true
      - type: HorizontalCategory
        category: Infrastructure Deployments
        rows: 3
        width: 370
        height: 120
        top: 170
        left: 480
        color: rgb(126,115,14)
        fit_width: true
      - type: HorizontalCategory
        category: Container Registry & Build
        rows: 3
        width: 400
        height: 120
        top: 300
        left: 0
        color: rgb(87,43,10)
        fit_width: true
      - type: HorizontalCategory
        category: DevSecOps
        rows: 3
        width: 230
        height: 120
        top: 300
        left: 420
        color: rgb(193,83,21)
        fit_width: true
      - type: HorizontalCategory
        category: Observability and Analysis
        rows: 3
        width: 530
        height: 120
        top: 300
        left: 670
        color: rgb(185,33,66)
        fit_width: true
      - type: HorizontalCategory
        category: CDF Members
        rows: 8
        width: 900
        height: 200
        top: 430
        left: 0
        color: rgb(179,60,133)
        fit_width: true
      - type: LandscapeInfo
        width: 335
        height: 140
        top: 150
        left: 865
        children:
          - type: text
            text: >
              This landscape is intended as a map to explore the Continuous Delivery community, and also shows the member organizations of the Continous
              Delivery Foundation.
            top: 40
            left: 105
            right: 10
            font_size: 10
          - type: image
            image: qr.svg
            top: 30
            left: 15
            width: 80
            height: 80
            title: QR Code
          - type: title
            title: l.cd.foundation
            top: 6
            left: 8
            font_size: 15
          - type: image
            image: left-logo.svg
            width: 85
            right: 130
            top: 5
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 110
            right: 5
            top: 5
            title: CD Foundation Logo
      - type: LandscapeLink
        url: https://landscape.cncf.io
        image: https://landscape.cncf.io/images/landscape_preview.png
        title: CNCF Landscape
        layout: subcategory
        left: 920
        top: 430
        width: 280
        height: 200
        color: rgb(64,117,191)
test:
  header: Continuous Delivery Landscape
  section: CDF Members
  logo: tekton-pipelines.svg
update_server:
  ip: 147.75.106.211
  update_hour: 0
  update_minute: 0
prerender:
  projects: /borderless-mode?organization=continuous-delivery-foundation-cdf&grouping=organization
export: {}
